// apps/admin/src/app/login/login.component.ts
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { AuthService } from '@myin/shared/authentication';

@Component({
    selector: 'myin-login',
    templateUrl: './login.component.html',
})
export class LoginComponent implements OnInit {
    constructor(public auth: AuthService, private router: Router) {}

    ngOnInit(): void {
        this.auth.handleAuthCallback(window.location.href);
        if (this.auth.isAuthenticated()) {
            this.router.navigate(['/']);
        }
    }
}

<button (click)="auth.login('login')">Login</button>

// libs/japanese/feature/login/src/lib/Login.vue
<template>
    <div class="login">
        <v-btn data-cy-login-btn @click="login()">Login</v-btn>
    </div>
</template>

<script lang="ts">
import Vue from 'vue';
import { Component, Inject } from 'vue-property-decorator';
import { AuthService } from '@myin/shared/authentication';

@Component
export default class Login extends Vue {
    @Inject()
    private authService: AuthService;

    created() {
        this.authService.handleAuthCallback(window.location.href);
        if (this.authService.isAuthenticated()) {
            this.$router.push({ name: 'Home' });
        }
    }

    login() {
        this.authService.login();
    }
}
</script>
